version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: acs-postgres
    environment:
      POSTGRES_DB: acs_pass
      POSTGRES_USER: acs_user
      POSTGRES_PASSWORD: acs_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  app:
    build: .
    container_name: acs-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/acs_pass
      SPRING_DATASOURCE_USERNAME: acs_user
      SPRING_DATASOURCE_PASSWORD: acs_pass

volumes:
  pgdata:
